/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_times.h"

bool_t
xdr_long_string (XDR *xdrs, long_string *objp)
{
	register int32_t *buf;

	 if (!xdr_ls (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_half_long_string (XDR *xdrs, half_long_string *objp)
{
	register int32_t *buf;

	 if (!xdr_hls (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ls (XDR *xdrs, ls *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->str, 2048,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hls (XDR *xdrs, hls *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->str1, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->str2, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
