/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_TIMES_H_RPCGEN
#define _RPC_TIMES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct ls long_string;

typedef struct hls half_long_string;

struct ls {
	char str[2048];
};
typedef struct ls ls;

struct hls {
	char str1[1024];
	char str2[1024];
};
typedef struct hls hls;

#define RPC_TIMES 1
#define RPC_TIMES_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define RPC_CALL_4 1
extern  int * rpc_call_4_1(int *, CLIENT *);
extern  int * rpc_call_4_1_svc(int *, struct svc_req *);
#define RPC_CALL_2048 2
extern  long_string * rpc_call_2048_1(half_long_string *, CLIENT *);
extern  long_string * rpc_call_2048_1_svc(half_long_string *, struct svc_req *);
extern int rpc_times_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RPC_CALL_4 1
extern  int * rpc_call_4_1();
extern  int * rpc_call_4_1_svc();
#define RPC_CALL_2048 2
extern  long_string * rpc_call_2048_1();
extern  long_string * rpc_call_2048_1_svc();
extern int rpc_times_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_long_string (XDR *, long_string*);
extern  bool_t xdr_half_long_string (XDR *, half_long_string*);
extern  bool_t xdr_ls (XDR *, ls*);
extern  bool_t xdr_hls (XDR *, hls*);

#else /* K&R C */
extern bool_t xdr_long_string ();
extern bool_t xdr_half_long_string ();
extern bool_t xdr_ls ();
extern bool_t xdr_hls ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_TIMES_H_RPCGEN */
