/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "msg_proto.h"

int *
printmessage_1_svc(char **argp, struct svc_req *rqstp) {
	static int result;

	result = 0;
	printf("%s\n", *argp);

	return &result;
}
